### PR TITLE
Fix start page map routing bug

### LINKED ISSUE #154: Start page segment routing bug in subpages

### LINKED ISSUE #299: Fix start page map routing bug
Kann bestätigen, der routing bug enstoht durch die map. I hob die map mol komplett entfernt. Do funktioniert alles einwandfrei.

### PR DESCRIPTION
**Pull request by b3h3m0th**
| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | yes                                             |
| New feature?         | no |
| Related issues/PRs   | closes #154, closes #299 |
| External ticket link |      |
| License              | MIT                                                |

### CODE REVIEW

File: libs/client/ui/pages/src/lib/start/map/go-to-location.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+}
+
+export const GoToLocation: React.FC<GoToLocationProps> = ({ location }) => {
+  const map = useMap();
+
+  return (
+    <IonButton
+      onClick={() => location && map.flyTo(location.latlng, 15)}
+      disabled={!location?.latlng}
+      className="start__content__map__gotolocation"
```
Comment (TimonStadelmann) [inline libs/client/ui/pages/src/lib/start/map/go-to-location.tsx:17]: Wenn scho an eigana Component denn o bitte eigenes SCSS

**Review by TimonStadelmann — APPROVED** [review]

File: libs/client/ui/pages/src/lib/start/map/go-to-location.tsx (hunk 1 above)
Comment (b3h3m0th) [reply libs/client/ui/pages/src/lib/start/map/go-to-location.tsx:17]: ajo true
